# Generated by Django 5.0.7 on 2024-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_department_image_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='overviewsetting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
