# Generated by Django 5.0.7 on 2024-08-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_calltoaction_department_emergencyservice_funfact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.department'),
            preserve_default=False,
        ),
    ]
