# Generated by Django 5.0.7 on 2024-08-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_appointment_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.service'),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmergencyService',
        ),
    ]
