# Generated by Django 5.0.7 on 2024-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_alter_schedule_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
