# Generated by Django 5.0.7 on 2024-08-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_rename_name_service_title_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpage',
            name='title',
        ),
        migrations.AddField(
            model_name='doctorpage',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.doctor'),
            preserve_default=False,
        ),
    ]
