# Generated by Django 5.0.7 on 2024-08-10 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_alter_schedule_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='overviewsection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='overviewsetting',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
