# Generated by Django 5.0.7 on 2024-08-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_remove_doctorpage_title_doctorpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpage',
            name='services',
        ),
        migrations.AddField(
            model_name='doctorpage',
            name='department',
            field=models.ManyToManyField(to='healthcare.department'),
        ),
    ]
