# Generated by Django 5.0.7 on 2024-08-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_appointment_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverviewSection',
        ),
        migrations.DeleteModel(
            name='OverviewSetting',
        ),
    ]
